CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_ZMK_INPUT_PROCESSOR_REPORT_RATE_LIMIT_DEFAULT=4

CONFIG_ZMK_SLEEP=n

# Prospector
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n

# Default layout
# CONFIG_PROSPECTOR_STATUS_SCREEN_DEFAULT=y
# OR Rounded Grid layout
# CONFIG_PROSPECTOR_STATUS_SCREEN_RADII=y
CONFIG_PROSPECTOR_STATUS_SCREEN_FIELD=y
# CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y#
# Show/Hide modifiers entirely
CONFIG_PROSPECTOR_SHOW_MODIFIERS=y
# Dim inactive modifiers instead of hiding them
CONFIG_PROSPECTOR_SHOW_INACTIVE_MODIFIERS=y
# Set the order (G=GUI, A=Alt, C=Ctrl, S=Shift)
# Default is "GACS"
CONFIG_PROSPECTOR_MODIFIER_ORDER="GASC"
# Choose Symbol Style
# Mac (Symbols: ⌘ ⌥ ⌃ ⇧)
CONFIG_PROSPECTOR_MODIFIER_OS_MAC=y
# Windows (Text: WIN ALT CTRL SHFT)
# CONFIG_PROSPECTOR_MODIFIER_OS_WINDOWS=y
# Generic (Text: GUI ALT CTRL SHFT)
# CONFIG_PROSPECTOR_MODIFIER_OS_GENERIC=y
