# Disable BLE on peripheral
CONFIG_ZMK_BLE=n

# Disable default split transports
CONFIG_ZMK_SPLIT_BLE=n

# Disable wired split
CONFIG_ZMK_SPLIT_WIRED=n

# Enable ESB split transport
CONFIG_ZMK_SPLIT_ESB=y

# Peripheral ID (unique per peripheral)
CONFIG_ZMK_SPLIT_ESB_PERIPHERAL_ID=1

# ESB protocol settings
CONFIG_ZMK_SPLIT_ESB_PROTO_TX_ACK=y

# MPSL timeslot
CONFIG_MPSL_TIMESLOT_SESSION_COUNT=1

# ESB stack requirements
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_ESB_MAX_PAYLOAD_LENGTH=64
CONFIG_ESB_TX_FIFO_SIZE=1

# ESB buffer
CONFIG_ZMK_SPLIT_ESB_EVENT_BUFFER_ITEMS=32
CONFIG_ZMK_SPLIT_ESB_PROTO_MSGQ_ITEMS=32

# Trackball & pointing
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PMW3610=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_PMW3610_SMART_ALGORITHM=y
CONFIG_PMW3610_REPORT_INTERVAL_MIN=4
CONFIG_ZMK_INPUT_PROCESSOR_REPORT_RATE_LIMIT_DEFAULT=4

# Battery reporting
CONFIG_ZMK_BATTERY_REPORTING=y
